### ISSUE TITLE
Translation is still broken

### ISSUE THREAD

**Issue by MasterixCZ** [rcmaehl/WhyNotWin11#257] opened 2021-06-29 19:42 UTC
Hi, I tested the Artifact and changed the file in Notepad as you advised in **#245**, but it still doesn't work :/ 
![image](https://user-images.githubusercontent.com/84620639/123857662-e50ecd00-d922-11eb-9426-dc9fb601a63f.png)

**Comment by micwoj92** [comment] 2021-06-29 19:50
Could you try:
1. remove all .lang files from that folder
2. reboot pc
3. test latest dev version (link in readme)

Reboot just to be sure, you never know ;p

**Comment by sebkopal** [comment] 2021-06-29 20:43
I tested Czech language on my real HW, Windows 10 installed with Slovak language as default
![image 1](https://user-images.githubusercontent.com/35070740/123863250-a597af00-d929-11eb-99bd-ea3be746dfd1.png)

Tested on VMWare as well, Windows 10 installed with EN-US language as default
![image2](https://user-images.githubusercontent.com/35070740/123863549-032bfb80-d92a-11eb-9e80-e45834c83fd5.png)

Or try this one
[0405.lang.txt](https://github.com/rcmaehl/WhyNotWin11/files/6736328/0405.lang.txt)

**Comment by micwoj92** [comment] 2021-06-29 20:50
@sebkopal could you also check Italian? Same issue was reported for it.

**Comment by micwoj92** [comment] 2021-06-29 21:14
@MasterixCZ closing as duplicate of #248

**Closed by micwoj92** 2021-06-29 21:14 UTC
Labels: bug
