### ISSUE TITLE
Secure Boot Requirement is wrong

### ISSUE THREAD

**Issue by werdnaa87** [rcmaehl/WhyNotWin11#14] opened 2021-06-25 14:46 UTC
Windows 11 requires Secure Boot be available, not enabled:

![image](https://user-images.githubusercontent.com/64870117/123442068-83f19d00-d5a2-11eb-837e-f74c5d3f4b0a.png)

![image](https://user-images.githubusercontent.com/64870117/123442109-8c49d800-d5a2-11eb-8aaf-0cc78c7bef09.png)

Both screenshots taken on the same machine obviously

**Comment by bl-ue** [comment] 2021-06-25 14:49
Duplicate of #8

**Comment by rcmaehl** [comment] 2021-06-25 16:31
Closing to not have a bunch of issues. Will be adding a note for this, however

**Closed by rcmaehl** 2021-06-25 16:31 UTC
Labels: duplicate, enhancement
