### ISSUE TITLE
WhyNotWin11_x86.exe v2.2.2 - Windows Defender - Trojan:Win32/Wacatac.B!ml 

### ISSUE THREAD

**Issue by grimson73** [rcmaehl/WhyNotWin11#61] opened 2021-06-27 09:27 UTC
Trojan:Win32/Wacatac.B!ml
Flagged by Windows Defender
https://github.com/rcmaehl/WhyNotWin11/releases/download/2.2.2/WhyNotWin11_x86.exe

**Comment by famo000** [comment] 2021-06-27 09:51
Autoit softwares are frenquently flaggge as virus.
Take source, compile it, and test again.

**Comment by rcmaehl** [comment] 2021-06-27 12:24
Duplicate of #49

**Closed by rcmaehl** 2021-06-27 12:24 UTC
Labels: duplicate, wontfix
