### ISSUE TITLE
2.3.0.1 NOT signed?

### ISSUE THREAD

**Issue by Aaron451** [rcmaehl/WhyNotWin11#244] opened 2021-06-29 17:03 UTC
error at startup Publisher: unknown

**Comment by rcmaehl** [comment] 2021-06-29 17:06
No builds have been signed. You can continue to the application by selecting "More Information" then "Run Anyway"

**Comment by rcmaehl** [comment] 2021-06-29 17:06
Closing as duplicate of #75

**Closed** 2021-06-29 17:06 UTC
