### ISSUE TITLE
WDDM 3.0 shown as incompatible

### ISSUE THREAD

**Issue by maggo1312** [rcmaehl/WhyNotWin11#42] opened 2021-06-26 21:01 UTC
WDDM 3.0 shown as incompatible
<img width="1151" alt="dx12_wddm3 0" src="https://user-images.githubusercontent.com/49472233/123525615-5c99ed80-d6d2-11eb-94e1-f8aa0fb1f500.png">

**Comment by micwoj92** [comment] 2021-06-26 21:02
Duplicate of #41 posted 3 minutes ago lol

**Comment by Gengar60** [comment] 2021-06-26 21:03
Oh sorry must have posted this while I was writing it!

**Closed** 2021-06-26 21:06 UTC
