### ISSUE TITLE
UI Display issue - Tick boxes not displaing corectly on v.2.3.1.0/2.3.1.1, was ok on 2.3.0.3

### ISSUE THREAD

**Issue by Anandakri** [rcmaehl/WhyNotWin11#521] opened 2021-07-18 16:44 UTC
**Describe the bug**
<br>A clear and concise description of what the bug is.

**To Reproduce**
<br>Steps to reproduce the behavior:

**Expected behavior**
<br>A clear and concise description of what you expected to happen.

**Screenshots**
<br>If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Version [e.g. 2.3.0.0]

**Additional context**
<br>Add any other context about the problem here.

**Comment by rcmaehl** [comment] 2021-07-18 17:03
Duplicate of #490

**Closed** 2021-07-18 17:03 UTC
