### ISSUE TITLE
WMI - DiskInfos: Incorrect detection with more than one Disk

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#162] opened 2021-06-28 23:14 UTC
We select on Bootpartition property which is problematic. This only indicates that the partition is marked as active. But not that it is the system partition of the bootet os.

Can be a problem if ext. bootable drives are connected.

We should use a more complex querry. 

Affected checks: GPT, Drive space

@rcmaehl 
I can upload a poc in powershell tomorrow. We can combine tables to detect the partition based on var $systemdrive.

**Comment by rcmaehl** [comment] 2021-06-29 00:19
That would be great.

**Comment by htcfreek** [comment] 2021-06-29 05:23
@rcmaehl 
Here we go. The example in Powershell code:
```powershell
$result=@()
$disks=gwmi -query "SELECT * FROM Win32_DiskDrive"
ForEach($disk in $disks){
    $partitions=gwmi -query "ASSOCIATORS OF {Win32_DiskDrive.DeviceID='$($disk.DeviceID)'} WHERE AssocClass = Win32_DiskDriveToDiskPartition"
    ForEach($partition in $partitions){
        $logicaldisks=gwmi -query "ASSOCIATORS OF {Win32_DiskPartition.DeviceID='$($partition.DeviceID)'} WHERE AssocClass = Win32_LogicalDiskToPartition"
        ForEach($logicaldisk in $logicaldisks){
                $result+=New-Object PSObject -Property @{
                'Partition'=$logicaldisk.DeviceID;
                'Type'=$partition.Type
                }
        }
    }
}
($result | Where-Object {$_.partition -eq $env:SystemDrive}).type -like "GPT*"
```

**Comment by htcfreek** [comment] 2021-06-29 15:09
@rcmaehl 
Please label as bug.

**Comment by micwoj92** [comment] 2021-06-29 16:37
Done, I knew it was a bug :roll_eyes:

**Comment by hajubu** [comment] 2021-06-29 20:29
Just avoid to use the PS sample above as of  the 'Result' is always FALSE ($partition.Type  value = "Installable File System"

# \\Computername\root\cimv2:Win32_DiskPartition.DeviceID="Disk #0, Partition #1" Installable File System
# \\Computername\root\cimv2:Win32_DiskPartition.DeviceID="Disk #1, Partition #0" Installable File System

A Powershell solution is using get-Disk  AND  gwmi .... combined
#################################################
Get-Disk | select Number,FriendlyName, PartitionStyle | Out-Host
#write-host ("pause ?"); $A=Read-Host ("->")

gwmi -query "Select * from Win32_DiskPartition WHERE  BootPartition=True "|`   #Index = 0  
            Select-Object DiskIndex, @{Name="GPT";Expression={$_.Type.StartsWith("MBR")}} | out-Host
#write-host ("pause ?"); $A=Read-Host ("->")
#################################################
Number FriendlyName                  PartitionStyle
------ ------------                  --------------
     1 Samsung SSD 850 EVO mSATA 1TB MBR           
     0 Samsung SSD 850 PRO 256GB     MBR           
     2 EPSON Storage                 RAW           

DiskIndex   GPT
---------   ---
        0      False

b.r. Hajubu

**Comment by micwoj92** [comment] 2021-06-29 21:10
@hajubu Formatted your post into code block so it displays nice, you can do this by typing this character under tilde key three times ` .

**Comment by hajubu** [comment] 2021-06-29 21:20
> @hajubu Formatted your post into code block so it displays nice, you can do this by typing this character under tilde key three times ` .

Sorry for the add -work ; Thanks 😊👍

**Comment by htcfreek** [comment] 2021-06-30 01:36
> Just avoid to use the PS sample above as of  the 'Result' is always FALSE
> ```pwsh
> ($partition.Type  value = "Installable File System"
> 
> # \\Computername\root\cimv2:Win32_DiskPartition.DeviceID="Disk #0, Partition #1" Installable File System
> # \\Computername\root\cimv2:Win32_DiskPartition.DeviceID="Disk #1, Partition #0" Installable File System
> ```
> A Powershell solution is using get-Disk  AND  gwmi .... combined
> 
> ```pwsh
> #################################################
> Get-Disk | select Number,FriendlyName, PartitionStyle | Out-Host
> #write-host ("pause ?"); $A=Read-Host ("->")
> 
> gwmi -query "Select * from Win32_DiskPartition WHERE  BootPartition=True "|`   #Index = 0  
>             Select-Object DiskIndex, @{Name="GPT";Expression={$_.Type.StartsWith("MBR")}} | out-Host
> #write-host ("pause ?"); $A=Read-Host ("->")
> #################################################
> Number FriendlyName                  PartitionStyle
> ------ ------------                  --------------
>      1 Samsung SSD 850 EVO mSATA 1TB MBR           
>      0 Samsung SSD 850 PRO 256GB     MBR           
>      2 EPSON Storage                 RAW           
> 
> DiskIndex   GPT
> ---------   ---
>         0      False
> ```
> b.r. Hajubu
> 
> 

1. We don't want to implement PowerShell code. It's only an example written in Powershell.
2. Why do you think my code will return always false? (It's only false if the disk with your system drive is not GPT.)

**Comment by hajubu** [comment] 2021-06-30 07:22
> 1. We don't want to implement PowerShell code. It's only an example written in Powershell.
      Sample PS-Code  Only - YES - implementation in WhynotWin11 to avoid in general.

> 2. Why do you think my code will return always false? (It's only false if the disk with your system drive is not GPT.)
      Probavly - I was trapped in my Mockup Test environment .
         Testing again showed YOU are right .

     I try to dig deeper in the case for a better support of the task.
     Sorry for the misleading comments. 
b.r. Hajubu

**Comment by htcfreek** [comment] 2021-07-01 18:59
@rcmaehl 
Working on it. Please add "in progress".

**Comment by micwoj92** [comment] 2021-07-01 19:00
Added in progress and assigned to you.

**Comment by htcfreek** [comment] 2021-07-01 19:09
@rcmaehl 
Which license do you want to have?

**Comment by micwoj92** [comment] 2021-07-01 19:55
@htcfreek What makes you not wanna use LGPL?

**Comment by htcfreek** [comment] 2021-07-01 19:56
> @htcfreek What makes you not wanna use LGPL?

I read a bit and decided to switch to lgpl. 😉

**Comment by htcfreek** [comment] 2021-07-01 20:28
@rcmaehl 
Here is an new function to get disk infos from wmi: https://github.com/htcfreek/AutoIT-Scripts/blob/v1.0/src/GetDiskInfoFromWmi.au3

=> Note: You can disable the table headers.

![image](https://user-images.githubusercontent.com/61519853/124185725-9f393c80-dabb-11eb-981a-859fbec19a26.png)

![image](https://user-images.githubusercontent.com/61519853/124185781-b4ae6680-dabb-11eb-835d-5c08ad03e42c.png)

**Comment by htcfreek** [comment] 2021-07-01 20:54
@rcmaehl 
I think it would be better if you implement the new function because you have a better overview on the main script and checks. 😉

**Comment by htcfreek** [comment] 2021-07-02 05:18
@rcmaehl 
I have released the new version: https://github.com/htcfreek/autoit-scripts/releases/latest

**Comment by htcfreek** [comment] 2021-07-03 14:14
Please reassign it to me. Will work tomorrow on it.

**Comment by rcmaehl** [comment] 2021-07-03 21:12
@htcfreek Let me see if I can implement this.

**Comment by rcmaehl** [comment] 2021-07-03 21:29
@htcfreek Merged in. Sorry my github notifications are a mess. Feel free to open a PR or ping me on github as older issues might get passed up on accident. 😅

**Comment by htcfreek** [comment] 2021-07-03 21:53
@rcmahel 
I think I will release v1.2 tomorrow with an small enhancement. So I will look tomorrow on it.

But I saw you didn't removed the old check from wmi and you only changed one check in main script. Is this correct?

**Comment by rcmaehl** [comment] 2021-07-03 21:58
> @rcmahel
> I think I will release v1.2 tomorrow with an small enhancement. So I will look tomorrow on it.
> 
> But I saw you didn't removed the old check from wmi and you only changed one check in main script. Is this correct?

For now, this may improve one I get it sorted out, something like

$SYSTEM_DISK - "GPT DETECTED"
#/# Disks Meet Requirements

**Comment by htcfreek** [comment] 2021-07-03 21:59
@rcmaehl 
Try the latest dev build: The result on success check isn't centered anymore.

OFFTOPIC: Is the disk space requirement for Windows 11 for partitions or for disks?

**Comment by rcmaehl** [comment] 2021-07-03 22:00
> @rcmaehl
> Try the latest dev build: The result on success check isn't centered anymore.
> 
> OFFTOPIC: Is the disk space requirement for Windows 11 for partitions or for disks?

Partition, but we can "Warn" if the Disk has enough space but the partition does not.

**Comment by htcfreek** [comment] 2021-07-03 22:00
> > @rcmahel
> > I think I will release v1.2 tomorrow with an small enhancement. So I will look tomorrow on it.
> > But I saw you didn't removed the old check from wmi and you only changed one check in main script. Is this correct?
> 
> For now, this may improve one I get it sorted out, something like
> 
> $SYSTEM_DISK - "GPT DETECTED"
> #/# Disks Meet Requirements

I panned to do this tomorrow. I planed nearly the same. 😅

**Comment by htcfreek** [comment] 2021-07-03 22:02
> > @rcmaehl
> > Try the latest dev build: The result on success check isn't centered anymore.
> > OFFTOPIC: Is the disk space requirement for Windows 11 for partitions or for disks?
> 
> Partition, but we can "Warn" if the Disk has enough space but the partition does not.

I can implement it tomorrow.  Let me create a new issue for improving layout (and check) of gpt and disk space

**Comment by micwoj92** [comment] 2021-07-04 01:01
Sadly, this broke running on Wine, which worked fine prior to https://github.com/rcmaehl/WhyNotWin11/commit/f913e4486599f7d92498e708f65292a10de69972

**Comment by rcmaehl** [comment] 2021-07-04 01:11
> Sadly, this broke running on Wine, which worked fine prior to [f913e44](https://github.com/rcmaehl/WhyNotWin11/commit/f913e4486599f7d92498e708f65292a10de69972)
> ![image](https://user-images.githubusercontent.com/45581170/124370132-28936f00-dc74-11eb-9fb6-71589f1391fe.png)

I'm pretty sure you get a different pop-up before this one can you post that

**Comment by micwoj92** [comment] 2021-07-04 01:12
Only loading, but it quits and then just shows this

**Comment by micwoj92** [comment] 2021-07-04 01:13
line 1279
`Local $sNewDisk = $iDisk & "||" & $oDisk.DeviceID & "||" & $oDisk.Manufacturer & "||" & $oDisk.Model & "||" & $oDisk.Interfacetype & "||" & $oDisk.Mediatype & "||" & $oDisk.Serialnumber & "||" & $oDisk.Status & "||" & $oDisk.Size & "||" & "<DiskInitStyle>" & "||" & $oDisk.Partitions & "||" & False`

**Comment by micwoj92** [comment] 2021-07-04 01:16
I think this is wine error
```
0058:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0058:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
```

**Comment by micwoj92** [comment] 2021-07-04 12:30
Still broken, honestly it's not worth it to support wine
![image](https://user-images.githubusercontent.com/45581170/124385033-514b5100-dcd4-11eb-8d66-b293cd7e26d8.png)

**Comment by htcfreek** [comment] 2021-07-04 12:51
> Still broken, honestly it's not worth it to support wine
> ![image](https://user-images.githubusercontent.com/45581170/124385033-514b5100-dcd4-11eb-8d66-b293cd7e26d8.png)

Maybe the ASSOC tables not existing in wine.

**Comment by htcfreek** [comment] 2021-07-05 22:39
Let's close as dup of #385. 

Imo the wine problem is a won't fix. Running this tool in wine isn't a real use case!

**Comment by micwoj92** [comment] 2021-07-05 22:54
Ok, closing as duplicate of #385 then. Also locking, as further discussion should go there.

**Closed by micwoj92** 2021-07-05 22:54 UTC
Labels: bug, patched?
