### ISSUE TITLE
GPT detection not working correctly

### ISSUE THREAD

**Issue by IvanAclu** [rcmaehl/WhyNotWin11#193] opened 2021-06-29 08:08 UTC
GPT correctly detected in previous versions up to 2.2.4.5.
Not detected in 2.3.0.
My PC has 2 disks, OS disk is GPT other disk is MBR

**Comment by PrototypeGR** [comment] 2021-06-29 08:23
+1 something is wrong

**Comment by htcfreek** [comment] 2021-06-29 11:53
Duplicate of #162.

**Closed** 2021-06-29 12:43 UTC
Labels: duplicate
