### ISSUE TITLE
Gui buttons don't work until the process is completed

### ISSUE THREAD

**Issue by Saman-Izadi** [rcmaehl/WhyNotWin11#73] opened 2021-06-27 14:36 UTC
There are 4 buttons in the gui, but none of them work until the checking process is done (all the results are out and there's no "checking" pending), if you click on the buttons before the process is done, they'll all get open after the checking is finished (I spammed the buttons as they were not working, oh god)
![image](https://user-images.githubusercontent.com/85870077/123548604-b1913e80-d77a-11eb-839b-49148612828d.png)
![image](https://user-images.githubusercontent.com/85870077/123548523-4d6e7a80-d77a-11eb-8ea7-8c04275ea4fd.png)

**Comment by rcmaehl** [comment] 2021-06-27 14:37
Duplicate of #39. Will work on that shortly

**Comment by Saman-Izadi** [comment] 2021-06-27 14:37
Oops, sorry!

**Closed** 2021-06-27 23:56 UTC
Labels: duplicate
