### ISSUE TITLE
exe v. 2.3.1 - Italian language file converterd in UTF-16 LE BOM

### ISSUE THREAD

**Issue by bovirus** [rcmaehl/WhyNotWin11#495] opened 2021-07-12 07:30 UTC
**Describe the bug**
<br>A clear and concise description of what the bug is.

Running the exevv. 2.3.1 on Windows 10 64bit the italian language (0410.lang) saved in Langs folder is coded as text UTF-16 LE BOM.
All other languages are coded as UTF-8.
All language file are about 3 to 4 KB.
Italian languages is about 10 KB.

**Comment by micwoj92** [comment] 2021-07-12 08:12
Shows 4.7 KiB (4,802 bytes) for me, so someone with Windows will have to confirm. There is absolutely ZERO need in pinging Robert in every issue you post. That will not make him open your issue faster.

**Comment by rcmaehl** [comment] 2021-07-13 02:30
FIle is showing UTF-8 for me as well. 
![image](https://user-images.githubusercontent.com/716581/125380619-7721c700-e360-11eb-89e4-da407aa93b1d.png)

Even cloned a fresh copy of the repo to be sure
![image](https://user-images.githubusercontent.com/716581/125380742-afc1a080-e360-11eb-8325-8858a93215d1.png)

**Comment by bovirus** [comment] 2021-07-13 04:51
Sorry but I knopw very well wahts is UTF-8 and UTF-16 LE.

List of file - Pelase checl file size

![image](https://user-images.githubusercontent.com/1262554/125392402-685e0300-e3a6-11eb-9b21-2afc0ae3ce66.png)

File is surely ITF16 LE for teh fiel size and for the file type

![image](https://user-images.githubusercontent.com/1262554/125392629-cdb1f400-e3a6-11eb-9aff-b75157d32eaa.png)

**Comment by rcmaehl** [comment] 2021-07-13 05:41
May be an issue with file opening. 1 moment

**Comment by rcmaehl** [comment] 2021-07-13 05:45
https://github.com/rcmaehl/WhyNotWin11/blob/c87e2247041fd1925cd51f7ebcbbb35756fd2fe7/includes/_Translations.au3#L60

https://www.autoitscript.com/autoit3/docs/functions/FileOpen.htm

Yeah, the file gets opened in UTF16-LE. I can see about changing this.

**Comment by krystian3w** [comment] 2021-07-13 22:37
My few files Notepad++ open in China 🇨🇳 encoding = "Big5".

**Comment by Nits77** [comment] 2021-07-14 15:24
I have checked lang files (which have all an average size of 3-5KB) and it's not related them. The file format for 0410 (it) and 040C (fr) are both UTF-8.

The issue appears when opening the executable, which will cause the lang file to be "converted" to another file format. I can confirm your point @rcmaehl.

@bovirus If you are a real software support guy, you should know that (what i have said above) by downloading the code and check the lang files without opening the executable (it did not take more than 2 minutes). Be correct with the community, that's not the first time i see your haughty messages, we are all here to make this software greater.

**Comment by bovirus** [comment] 2021-07-14 15:38
@Nits77

Pelase check my first post.

I never say that the problem are in the source code and language file in repository.

The problem is the compiled exe file. And you confirmed this.

When you ran it the file is converted from UTF-8 to UTTF-16LE.
This is my initial report. 

The problem is not mine.
It's about who answer to my first post without reading carefully my post.

**Comment by Nits77** [comment] 2021-07-14 17:30
@bovirus 
> Pelase check my first post.

I checked it and you didn't said that you were talking about the `Langs` folder located in `AppData/Local` :

> Running the version 2.3.1 the italian language (0410.lang) saved in Langs folder is coded as text UTF-16 LE BOM.

"Langs folder" doesn't mean `AppData/Local`, it can also be in the source code (which is also called "Langs"), it wasn't clear until your second post, that's why they answered you that files aren't UTF-16 as you described.



> I never say that the problem are in the source code and language file in repository.

I know, and that's why i answered you that you didn't checked in depth to find the issue, just reporting that "italian lang file is UTF-16 encoded" with unclear precisions for the "Langs" folder.


> But the initial answer are about language files on repository that is not subject of my post.

Because your initial report wasn't clear on the folder location.


> The problem is the compiled exe file. And you confirmed this.

Yes but it's not directly related to a single lang file, it's an overall issue.

@rcmaehl You can probably update the title due to the issue (not related to only one lang file) and add labels for this confirmed issue.

**Comment by micwoj92** [comment] 2021-07-14 17:57
Low because it doesn't affect any functionality. Should it even be issue at this point? And it probably does that for all the language files once you open wnw11 with specified language.

**Comment by bovirus** [comment] 2021-07-14 18:07
For me it's an issue.
If the original language files are UTF.8 the program shouldn't convert them in UTF16-LE.

**Comment by Nits77** [comment] 2021-07-14 18:58
@micwoj92 
> Low because it doesn't affect any functionality. Should it even be issue at this point? And it probably does that for all the language files once you open wnw11 with specified language.

Yes that's an issue. I agree with @bovirus that should not change the original file format.

I also agree with you for the low priority.

**Comment by rcmaehl** [comment] 2021-07-25 05:04
It appears this is an issue with WinAPI and AutoIt, not the script itself.  

https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page
https://stackoverflow.com/questions/504779/winapi-and-utf-8-support
https://www.reddit.com/r/cpp/comments/g7tkd7/state_of_utf8_support_on_windows/

I'm going to mark this as "won't fix"

**Closed by rcmaehl** 2021-07-25 05:04 UTC
Labels: bug, low, wontfix
