### ISSUE TITLE
VirusTotal / WhyNotWin11.zip v2.5.0.1 2022-7-7

### ISSUE THREAD

**Issue by Zaqm** [rcmaehl/WhyNotWin11#695] opened 2022-08-23 20:34 UTC
WhyNotWin11.zip = WhyNotWin11.exe + WhyNotWin11_x86.exe + checksums.sha256
.
WhyNotWin11.zip
https://www.virustotal.com/gui/file/394cdccc5ca9bd9c7f75652c7d8b627d58886940fddd87515c3d01fd9044570a
.
WhyNotWin11.exe
https://www.virustotal.com/gui/file/bf0eed3b0c52e3b7729d55a942d7a12f0481533090034f74e8082961eace4037
.
WhyNotWin11_x86.exe
https://www.virustotal.com/gui/file/37fa4ffea87e8ec172b71c4142fb2ebcaa79fa00576f8dfa0a4f7e6df53c0442
.
checksums.sha256
https://www.virustotal.com/gui/file/35f65e487ae32b2ffe48612c1db1a020dd236b324cb59ab64f0b6d11c34bbbae
.
Hi @rcmaehl
see this
Why does it have viruses ??

**Comment by rcmaehl** [comment] 2022-08-23 20:38
Duplicate of #49.

**Closed by rcmaehl** 2022-08-23 20:38 UTC
Labels: duplicate

**Comment by Zaqm** [comment] 2022-08-23 20:39
@rcmaehl Thank you
