### ISSUE TITLE
Add Backup GPT formatting check

### ISSUE THREAD

**Issue by akulisch** [rcmaehl/WhyNotWin11#29] opened 2021-06-26 12:44 UTC
I have three drives and all have a "Partition style" of "GUID Partition Table (GPT)" as reported by the Windows 10 Disc Management Tool. WhyNotWin11 v 2.1.0.0 still shows "GPT Not Detected" in the Disc Partitioning category with a failed status.

Example of the drive properties as reported by the Windows 10 Disc Management Tool. All other drives have the same entry there.
![image](https://user-images.githubusercontent.com/15906252/123513303-d313fc80-d68c-11eb-9961-d98219b594f1.png)

WhyNotWin11 report:
![image](https://user-images.githubusercontent.com/15906252/123513332-ffc81400-d68c-11eb-8ecb-ca70c442fa02.png)

**Comment by rcmaehl** [comment] 2021-06-26 16:21
Hi, can you run `Get-Partition -DriveLetter C | Get-Disk | Select-Object -Property PartitionStyle` in powershell and screenshot the output for me?

**Comment by htcfreek** [comment] 2021-06-26 16:37
Maybe this is more save and can done in Autoit or PwSh:
```powershell
Get-WmiObject Win32_DiskPartition -Filter "Bootpartition = 'True' " | Select Type
```

**Comment by akulisch** [comment] 2021-06-26 17:04
Those are the results for both commands on my system:
![image](https://user-images.githubusercontent.com/15906252/123520393-ca352200-d6b0-11eb-9362-210dd6468e70.png)

Rough translation of the error of the first command:
```
Get Partition : Could not find any MSFT_Partition objects where the DriveLetter property is equal to "C".
Check the value of the property and retry.
In Line:1 Char1
+ Get-Partition -DriveLetter C | Get-Disk | Select-Object -Property Par ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:Char) [Get-Partition], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_DriveLetter,Get-Partition```

**Comment by rcmaehl** [comment] 2021-06-26 17:06
I'll add in a backup check as suggested by @htcfreek

**Comment by rcmaehl** [comment] 2021-06-26 17:08
> Maybe this is more save and can done in Autoit or PwSh:
> 
> ```powershell
> Get-WmiObject Win32_DiskPartition -Filter "Bootpartition = 'True' " | Select Type
> ```

I'll have to narrow this somehow, as this will return all bootable disks.

**Comment by rcmaehl** [comment] 2021-06-26 17:10
Additionally, the Boot Loader / BootPartition may be on a different drive than C: for some multiboot systems.

**Comment by akulisch** [comment] 2021-06-26 17:11
> Additionally, the Boot Loader / BootPartition may be on a different drive than C: for some multiboot systems, but it's a backup check nonetheless.

I have a multi boot system with Windows 10 and a Manjaro Linux. Boot Drive is the Manjaro Drive with grub.

**Comment by htcfreek** [comment] 2021-06-26 17:19
> > Maybe this is more save and can done in Autoit or PwSh:
> > 
> > ```powershell
> > Get-WmiObject Win32_DiskPartition -Filter "Bootpartition = 'True' " | Select Type
> > ```
> 
> I'll have to narrow this somehow, as this will return all bootable disks.

You can use win32_logicaldisk to get drive with c partition.

**Comment by billysielu** [comment] 2021-06-27 17:49
My output for those two commands, as it's a bit different: 
![image](https://user-images.githubusercontent.com/59173811/123554512-4181b900-d778-11eb-9c63-4f1ae185991d.png)

**Comment by Masamune3210** [comment] 2021-06-27 18:42
is your boot drive some filesystem other than NTFS? IFS is used for filesystems not native to Windows

**Comment by billysielu** [comment] 2021-06-27 18:48
It's NTFS.

**Comment by MartinLondonUK77** [comment] 2021-06-28 13:49
GPT is not detected on 2.2.5.0 but it was detected correctly on previous versions of WhyNotWin11. My language is English (United Kingdom). I have run the PowerShell commands as above and confirmed the status of GPT.  DiskPart and WhyNotWin11 screenshots attached.
![DiskPart](https://user-images.githubusercontent.com/86610382/123646862-8280d880-d81f-11eb-990c-babf1b165a3a.jpg)
![WhyNotWin11](https://user-images.githubusercontent.com/86610382/123646867-83196f00-d81f-11eb-9e9f-2389a0c2d759.jpg)
![WhyNotWin11Old](https://user-images.githubusercontent.com/86610382/123647380-ef946e00-d81f-11eb-8716-81654c863ce2.jpg)

**Comment by rcmaehl** [comment] 2021-06-28 13:59
> GPT is not detected on 2.2.5.0 but it was detected correctly on previous versions of WhyNotWin11. My language is English (United Kingdom). I have run the PowerShell commands as above and confirmed the status of GPT. DiskPart and WhyNotWin11 screenshots attached.
> ![DiskPart](https://user-images.githubusercontent.com/86610382/123646862-8280d880-d81f-11eb-990c-babf1b165a3a.jpg)
> ![WhyNotWin11](https://user-images.githubusercontent.com/86610382/123646867-83196f00-d81f-11eb-9e9f-2389a0c2d759.jpg)
> ![WhyNotWin11Old](https://user-images.githubusercontent.com/86610382/123647380-ef946e00-d81f-11eb-8716-81654c863ce2.jpg)

Which 2.2.5 build are you using?

**Comment by rcmaehl** [comment] 2021-06-28 14:12
Please try a newer build

**Comment by MartinLondonUK77** [comment] 2021-06-28 14:12
> > GPT is not detected on 2.2.5.0 but it was detected correctly on previous versions of WhyNotWin11. My language is English (United Kingdom). I have run the PowerShell commands as above and confirmed the status of GPT. DiskPart and WhyNotWin11 screenshots attached.
> > ![DiskPart](https://user-images.githubusercontent.com/86610382/123646862-8280d880-d81f-11eb-990c-babf1b165a3a.jpg)
> 
> Which 2.2.5 build are you using?

I was running 2.2.5.0, having downloaded and recompiled - the screenshot is above. 

I downloaded and recompiled again just now (the comment in GitHub listed '#100') and now it is working! Strange... It's weird as you can see the version numbers in the second screenshot in my first post and the one below, they are the same. 

Before redownloading I even rebooted and recompiled the original 2.2.5.0 download and it still came up with error. 

But seems to be fixed now. See below screenshot as confirmation that it works. 👍
 
![WhyNotWin11-New2 2 5 0](https://user-images.githubusercontent.com/86610382/123650223-48fd9c80-d822-11eb-9bc6-1c669d65f817.jpg)

**Comment by MartinLondonUK77** [comment] 2021-06-28 14:18
> Please try a newer build

This is build #29, looks good.

![WhyNotWin11-New2 2 5 0#29](https://user-images.githubusercontent.com/86610382/123652279-118fef80-d824-11eb-9b59-2cba8e4ddf84.jpg)

**Comment by htcfreek** [comment] 2021-06-28 14:32
> Those are the results for both commands on my system:
> ![image](https://user-images.githubusercontent.com/15906252/123520393-ca352200-d6b0-11eb-9362-210dd6468e70.png)
> 
> EDIT: Administrator mode doesn't change results.
> 
> Rough translation of the error of the first command:
> ```
> Get Partition : Could not find any MSFT_Partition objects where the DriveLetter property is equal to "C".
> Check the value of the property and retry.
> In Line:1 Char1
> + Get-Partition -DriveLetter C | Get-Disk | Select-Object -Property Par ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (C:Char) [Get-Partition], CimJobException
>     + FullyQualifiedErrorId : CmdletizationQuery_NotFound_DriveLetter,Get-Partition```
> 

@akulisch 
Your command is incorrect. You have to write `C:` .

**Comment by htcfreek** [comment] 2021-06-28 23:26
@rcmaehl 
Could be closed as committed?

**Comment by rcmaehl** [comment] 2021-06-28 23:26
Yep. Thank you

**Closed by rcmaehl** 2021-06-28 23:26 UTC
Labels: bug, help wanted
