### ISSUE TITLE
Investigate Rare Weird UAC issue

### ISSUE THREAD

**Issue by kneelesh48** [rcmaehl/WhyNotWin11#9] opened 2021-06-25 13:12 UTC
I downloaded the exe file from the releases file and ran it. Nothing happened by the File Explorer stopped responding.

I restarted Windows Explorer and tried this several times. Same thing happens. Anyone else experiencing this?

I'm running dev channel
Edition	Windows 10 Pro
Version	Dev
Installed on	‎5/‎7/‎2021
OS build	21376.1
Experience	Windows 10 Feature Experience Pack 321.11803.0.3

**Comment by micwoj92** [comment] 2021-06-25 13:43
Come on microsoft, it even works on wine.

**Comment by rcmaehl** [comment] 2021-06-25 16:29
Sounds like Explorer was unable to launch a UAC prompt or smartscreen got stuck processing. Can you check Reliability History and see if there's a explorer.exe crash details at all. I'll keep this open but I think this may be outside of my control

**Comment by kneelesh48** [comment] 2021-06-26 04:39
The exe file downloaded from the releases file didn't run. I didn't get a UAC prompt and Explorer stopped responding.

But I installed AutoIt and cloned the repo and ran the .au3 file and it worked.

**Comment by MagicAndre1981** [comment] 2021-06-27 08:23
this is caused by Defender, use a better AV tool like NOD32

**Comment by rcmaehl** [comment] 2021-06-27 15:06
I haven't received any additional reports of this issue. I'm closing it for now.

**Closed by rcmaehl** 2021-06-27 15:06 UTC
Labels: external cause, help wanted
