### ISSUE TITLE
GPT not detected 

### ISSUE THREAD

**Issue by rajibms** [rcmaehl/WhyNotWin11#95] opened 2021-06-28 06:19 UTC
Its showing Disk Partition Type - GPT Not Detected 
But my partition is GPT

Why happening this?
![Screenshot 2021-06-28 121747](https://user-images.githubusercontent.com/44577660/123589462-14321b00-d80b-11eb-8a5a-73ba18269fa3.png)

**Comment by micwoj92** [comment] 2021-06-28 06:38
Duplicate of #53

**Closed by micwoj92** 2021-06-28 06:38 UTC
