### ISSUE TITLE
AV blocking release 2.3.0.1

### ISSUE THREAD

**Issue by Djinada** [rcmaehl/WhyNotWin11#221] opened 2021-06-29 13:11 UTC
Following is blocked by F-Secure.

https://www.f-secure.com/v-descs/w32_malware.shtml

Edit: [variant] is W32/Malware!Deepguard.a!fsmind

**Comment by rcmaehl** [comment] 2021-06-29 13:22
Duplicate of #49 . Please try the one without `x86` when possible

**Closed** 2021-06-29 13:22 UTC
Labels: duplicate

**Comment by Djinada** [comment] 2021-06-29 16:25
This occurred with the 64-bit version, should've specified this.

**Comment by micwoj92** [comment] 2021-06-29 17:01
I would still say that it is false positive. Contact the AV vendor and hope for quick fix.
