### ISSUE TITLE
Multiple MBR Disks reports "GPT Detected, 0/1"

### ISSUE THREAD

**Issue by Stewie410** [rcmaehl/WhyNotWin11#375] opened 2021-07-03 14:46 UTC
**Describe the bug**

When the latest release is run against a system with multiple MBR disks, the disk partition table requirement reports "GPT Detected 0/1 Drive(s) Meet Requirements".

**To Reproduce**
1. Have multiple non-GPT disks
2. Run the application

**Expected behavior**
I would expect the tool to report that GPT is not detected on any connected disk, as described in [line 628](https://github.com/rcmaehl/WhyNotWin11/blob/5df29572c00adbc7e92c96ca46000feff027fc42/WhyNotWin11.au3#L628)

**Screenshots**

![image](https://user-images.githubusercontent.com/24593067/124357716-06094380-dbeb-11eb-96c6-d34407b07616.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Version 21H1 (Build 19043.1081)

**Additional context**
I believe this issue is related to #162 -- though because of my configuration (no GPT disks at all), I'm unsure if `_GetDiskInfo` is handling multiple MBR drives appropriately.

**Comment by htcfreek** [comment] 2021-07-03 15:08
Will be fixed soon.

Duplicate of #

**Comment by micwoj92** [comment] 2021-07-03 15:24
Marking as duplicate, follow #162 

@htcfreek you are already assigned there, I don't think there is need for these 2 issues open if they are about the same thing.

**Closed by micwoj92** 2021-07-03 15:24 UTC

**Comment by htcfreek** [comment] 2021-07-03 15:26
Agree to you. It is linked, so I can't miss it. 😉
