### ISSUE TITLE
Norton 360 treats the software as malicious

### ISSUE THREAD

**Issue by dmitriy1980** [rcmaehl/WhyNotWin11#684] opened 2022-06-29 17:14 UTC
Every time I download 64-bit zip file, Chrome 103.0.5060.53 (and going back to at least version 97) treats is as malicious file.

When I bypass it and download the zip, when I extract it, Norton 360 finds the exe file as malicious and I need to exclude it from a scan in order to execute exe file. This is not a new issue and has been going on for months, I just did not have a chance to report it.

**Comment by micwoj92** [comment] 2022-06-29 17:15
Duplicate of https://github.com/rcmaehl/WhyNotWin11/issues/49

**Closed by micwoj92** 2022-06-29 17:15 UTC

**Comment by dmitriy1980** [comment] 2022-06-29 17:17
so, what is the solution?

**Comment by micwoj92** [comment] 2022-06-29 17:18
Report it to Norton as false positive

**Comment by rcmaehl** [comment] 2022-06-29 17:19
I'm doing so for them

**Comment by rcmaehl** [comment] 2022-06-29 17:20
![image](https://user-images.githubusercontent.com/716581/176497672-9d739c44-66a4-464b-93c9-852e3026f85a.png)
